import { StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  container: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 24 },
  brandSection: { alignItems: 'center', marginBottom: 48, gap: 10 },
  logoContainer: {
    width: 80,
    height: 80,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  appName: { fontSize: 32, fontFamily: 'Inter_700Bold' },
  tagline: { fontSize: 15, fontFamily: 'Inter_400Regular', textAlign: 'center' },
  formSection: { gap: 14 },
  inputWrapper: { position: 'relative' },
  inputIcon: { position: 'absolute', left: 14, top: 15, zIndex: 1 },
  input: {
    fontSize: 15,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 42,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
  },
  submitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 16,
    borderRadius: 14,
    marginTop: 6,
  },
  submitBtnText: { fontSize: 16, fontFamily: 'Inter_700Bold' },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
    marginTop: 24,
  },
  footerText: { fontSize: 14, fontFamily: 'Inter_400Regular' },
  footerLink: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
});

export const registerStyles = StyleSheet.create({
  container: { flex: 1 },
  content: { flex: 1, paddingHorizontal: 24 },
  brandSection: { marginBottom: 36, gap: 6 },
  backBtn: { marginBottom: 20 },
  title: { fontSize: 28, fontFamily: 'Inter_700Bold' },
  subtitle: { fontSize: 15, fontFamily: 'Inter_400Regular' },
  formSection: { gap: 14 },
  inputWrapper: { position: 'relative' },
  inputIcon: { position: 'absolute', left: 14, top: 15, zIndex: 1 },
  input: {
    fontSize: 15,
    fontFamily: 'Inter_400Regular',
    paddingHorizontal: 42,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
  },
  submitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 16,
    borderRadius: 14,
    marginTop: 6,
  },
  submitBtnText: { fontSize: 16, fontFamily: 'Inter_700Bold' },
  footer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
    marginTop: 24,
  },
  footerText: { fontSize: 14, fontFamily: 'Inter_400Regular' },
  footerLink: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
});
