import { StyleSheet } from 'react-native';

export const createContentModalStyles = StyleSheet.create({
  modalContentScroll: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 40,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    minHeight: 40,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingRight: 8,
  },
  backBtnText: {
    fontSize: 15,
    fontFamily: 'Inter_600SemiBold',
  },
  headerSpacer: { width: 72 },
  typeGrid: { gap: 12, marginTop: 8 },
  typeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
  },
  typeCardTextBlock: { flex: 1, gap: 4 },
  typeCardTitle: { fontSize: 17, fontFamily: 'Inter_700Bold' },
  typeCardSubtitle: { fontSize: 13, fontFamily: 'Inter_400Regular', lineHeight: 18 },
  scrollInner: { gap: 16, paddingBottom: 24 },
  pickerSection: { gap: 8 },
  pickerLabel: { fontSize: 13, fontFamily: 'Inter_500Medium', paddingLeft: 4 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  groupChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
  },
  groupChipText: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  memberList: { gap: 6, maxHeight: 200 },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
  },
  memberName: { fontSize: 15, fontFamily: 'Inter_600SemiBold' },
  memberId: { fontSize: 12, fontFamily: 'Inter_400Regular', marginTop: 2 },
  emptyMembers: { fontSize: 13, fontFamily: 'Inter_400Regular', paddingVertical: 8, paddingLeft: 4 },
  deadlinePressable: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
  },
  deadlineText: { fontSize: 15, fontFamily: 'Inter_400Regular' },
  attachRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  attachTextBlock: { flex: 1, gap: 4 },
  attachTitle: { fontSize: 14, fontFamily: 'Inter_600SemiBold' },
  attachHint: { fontSize: 12, fontFamily: 'Inter_400Regular' },
  webDatetimeWrap: { width: '100%' },
});
